-- Drop existing schema if it exists
DROP DATABASE IF EXISTS `warehouse`;
CREATE DATABASE `warehouse`;
USE `warehouse`;
DROP TABLE IF EXISTS `Sales`, `Products`, `Customers`, 
    `Stores`, `Suppliers`, `Time`;


-- Create tables
CREATE TABLE `Products` (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_PRICE DECIMAL(10, 2)
);

CREATE TABLE `Customers` (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255),
    GENDER VARCHAR(10)
);

CREATE TABLE `Stores` (
    STORE_ID INT PRIMARY KEY,
    STORE_NAME VARCHAR(255)
);

CREATE TABLE `Suppliers` (
    SUPPLIER_ID INT PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(255)
);

CREATE TABLE `Time` (
    time_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_DATE DATE NOT NULL UNIQUE,
    DAY VARCHAR(10),   
    MONTH INT,
    QUARTER INT,
    YEAR INT,
    SEASON VARCHAR(10),
    WEEKDAY BOOLEAN
);

CREATE TABLE `Sales` (
    ORDER_ID INT PRIMARY KEY,
    PRODUCT_ID INT,
    CUSTOMER_ID INT,
    STORE_ID INT,
    SUPPLIER_ID INT,
    TIME_ID INT, -- Foreign key referencing Time table
    QUANTITY INT,
    PRODUCT_PRICE DECIMAL(10, 2),
    SALE DECIMAL(15, 2),
    FOREIGN KEY (PRODUCT_ID) REFERENCES `Products`(PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES `Customers`(CUSTOMER_ID),
    FOREIGN KEY (STORE_ID) REFERENCES `Stores`(STORE_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES `Suppliers`(SUPPLIER_ID),
    FOREIGN KEY (TIME_ID) REFERENCES `Time`(time_ID)
);
